name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create config with secret
      run: |
        echo "const config = { TOKEN_INYECTADO: '${{ secrets.LIGUILLA }}' };" > js/config.secrets.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.LIGUILLA }}
        publish_dir: .
