name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Inyectar el token secreto en el archivo de configuración
      run: |
        echo "export const TOKEN = '${{ secrets.LIGUILLA }}';" > js/token.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.LIGUILLA }}
        publish_dir: .
