name: Guardar Predicci贸n

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Datos de la predicci贸n (en JSON)'
        required: true

jobs:
  guardar-prediccion:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar credenciales
      env:
        GITHUB_TOKEN: ${{ secrets.LIGUILLA }}

    - name: Crear una predicci贸n
      run: |
        echo "Guardando predicci贸n en el repositorio..."
