name: Guardar Predicción

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Datos de la predicción en formato JSON'
        required: true

jobs:
  guardar-prediccion:
    runs-on: ubuntu-latest

    steps:
    - name: Decodificar predicción
      run: echo "${{ github.event.inputs.data }}" > prediccion.json

    - name: Crear issue en GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.LIGUILLA }}
      run: |
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d @prediccion.json \
          "https://api.github.com/repos/${{ github.repository }}/issues"
